public class compare {
    public static void get(){
        list<contact> con = new list<contact>();
        contact con1 = new contact(firstname='ash', lastname='qwe');
        contact con2 = new contact(firstname='gash', lastname='qwe');
        contact con3 = new contact(firstname='nash', lastname='hqwe');
        contact con4 = new contact(firstname='mash', lastname='pqwe');
        con.add(con1);con.add(con2);con.add(con3);con.add(con4);
        insert con;
    }
}